[Paths]
clinvar = "data/raw/variant_summary.txt.gz"
fasta = "data/raw/GCF_000001405.40_GRCh38.p14_genomic.fna"
go = "data/processed/go_n2v_genes.npz"
artifacts = "artifacts/full"

[DNA]
model_id = "InstaDeepAI/nucleotide-transformer-500m-1000g"
window = 512
max_length = 512
batch_size = 16
pool = "mean"
force_windows = false
force_embeddings = false

[Protein]
model_id = "facebook/esm2_t12_35M_UR50D"
batch_size = 8
max_length = 2048
pool = "mean"
vep_cache_dir = "/home/zeus/vep_cache"
vep_fasta_relpath = "homo_sapiens/115_GRCh38/Homo_sapiens.GRCh38.dna.toplevel.fa.gz"
image = "ensemblorg/ensembl-vep"
use_docker = true
chunk_size = 2500
jobs = 18
vep_fork = 0
force_embeddings = false
force_vep = false

[GO]
npz = "data/processed/go_n2v_genes.npz"
normalize = false
uppercase_keys = true

[LLM]
enabled = true
out_dir = "artifacts/full/qwen3"
model_id = "Qwen/Qwen3-4B-Instruct-2507"
epochs = 1
max_len = 256
per_device_bs = 24
grad_accum = 8
lr = 0.0003
seed = 42
num_workers = 0
prefetch_factor = 2
persistent_workers = false
pin_memory = true
group_by_length = false
drop_last = true
balanced_sampling = true
n_cond_tokens = 8
prompt_dropout_prob = 0.3

[Run]
manifest = "artifacts/full/pipeline_manifest.json"
write_manifest = true
force_splits = false
force_dna_windows = false
force_dna_embeddings = false
force_protein_embeddings = false
device = "auto"
